#!/bin/bash

curl 'https://www.brownbearsw.com/cal/mband?Format=rss;Op=RSS' -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0' -H 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8' -H 'Accept-Language: en-US,en;q=0.5' --compressed -H 'Connection: keep-alive' -H 'Cookie: bbswcal_s=1566667985.82602%3ABQkDAAAAAA%3D%3D%3A69b4d525a005572cbd5ad341c3df20de89e0c1b8' -H 'Upgrade-Insecure-Requests: 1' -H 'DNT: 1' -H 'Pragma: no-cache' -H 'Cache-Control: no-cache' -o calinfo.txt

grep "<title>" calinfo.txt > cleaninfo.txt

if [ -f events.txt ]
then
    rm events.txt
fi


for ((i=0; i<$1;i++)); do date -d "+$i day" | cut -b 5-10  |grep -f - calinfo.txt | grep title >> events.txt; done


exit 0
